/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import consumindows.ConsumindoServicos;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lucastsuchiya and Pedro Bazia Neto
 */
public class JFormReserva extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    public JFormReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_reserva = new javax.swing.JTextPane();
        btn_reserva = new javax.swing.JButton();
        brn_passageiro = new javax.swing.JButton();
        bnt_motorista = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_passageiro = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_motorista = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva");

        jLabel1.setText("Reserva");

        jScrollPane1.setViewportView(txt_reserva);

        btn_reserva.setText("Listar Reservas");
        btn_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservaActionPerformed(evt);
            }
        });

        brn_passageiro.setText("Listar Passageiros");
        brn_passageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_passageiroActionPerformed(evt);
            }
        });

        bnt_motorista.setText("Listar Motoristas");
        bnt_motorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_motoristaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txt_passageiro);

        jScrollPane3.setViewportView(txt_motorista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reserva))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brn_passageiro)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnt_motorista))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnt_motorista)
                            .addComponent(brn_passageiro)
                            .addComponent(btn_reserva)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brn_passageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_passageiroActionPerformed
        try {
            // Listar todos dos passageiros
            ConsumindoServicos http = new ConsumindoServicos();
            String chamadaWS;
            chamadaWS = "http://127.0.0.1:5000/passageiros";
            String json = http.envioGet(chamadaWS);
            System.out.println(json);
            txt_passageiro.setText(json);
        } catch (Exception ex) {
            Logger.getLogger(JFormReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brn_passageiroActionPerformed

    private void btn_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservaActionPerformed
        try {
            // Listando todas as reservas
            ConsumindoServicos http = new ConsumindoServicos();
            String chamadaWS;
            chamadaWS = "http://127.0.0.1:5000/reservas";
            String json = http.envioGet(chamadaWS);
            System.out.println(json);
            txt_reserva.setText(json);
        } catch (Exception ex) {
            Logger.getLogger(JFormReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_reservaActionPerformed

    private void bnt_motoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_motoristaActionPerformed
        try {
            //Listanto todos os motoristas. 
            ConsumindoServicos http = new ConsumindoServicos();
            String chamadaWS;
            chamadaWS = "http://127.0.0.1:5000/motoristas";
            String json = http.envioGet(chamadaWS);
            System.out.println(json);
            txt_motorista.setText(json);
        } catch (Exception ex) {
            Logger.getLogger(JFormReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bnt_motoristaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_motorista;
    private javax.swing.JButton brn_passageiro;
    private javax.swing.JButton btn_reserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane txt_motorista;
    private javax.swing.JTextPane txt_passageiro;
    private javax.swing.JTextPane txt_reserva;
    // End of variables declaration//GEN-END:variables
}
