/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import consumindows.ConsumindoServicos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Motorista;
import modelo.Passageiro;
import modelo.Reserva;

/**
 *
 * @author Lucas Tsuchiya and Pedro Bazia Neto
 */
public class JFormPassageiro extends javax.swing.JFrame {

    /**
     * Creates new form Passageiro
     */
    public JFormPassageiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        txt_origem = new javax.swing.JTextField();
        txt_destino = new javax.swing.JTextField();
        txt_carro = new javax.swing.JTextField();
        txt_capacidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_preco = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_listarmotoristas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_motoristas = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        txt_idmotorista = new javax.swing.JTextField();
        btn_reserva = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_reserva = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passageiro");

        jLabel1.setText("Passageiro");

        jLabel2.setText("ID");

        jLabel3.setText("Nome");

        jLabel4.setText("Origem");

        jLabel5.setText("Destino");

        jLabel6.setText("Tipo de Carro");

        jLabel7.setText("Capacidade");

        jLabel8.setText("Preço R$");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_listarmotoristas.setText("Listar Motoristas");
        btn_listarmotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarmotoristasActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txt_motoristas);

        jLabel9.setText("Fazer Reserva:");

        btn_reserva.setText("Fazer Reserva");
        btn_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservaActionPerformed(evt);
            }
        });

        jLabel10.setText("ID Motorista");

        jLabel11.setText("ID Reserva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_carro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_origem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_cadastrar))))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(btn_reserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_idmotorista)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_reserva)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_listarmotoristas)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_carro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_listarmotoristas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_idmotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(txt_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reserva)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        try {
            // Cadastrando um passageiro 
            //Instanciando o objeto do tipo Passageiro
            Passageiro novo_passageiro = new Passageiro();
            
            //Pegado os dados do formulário 
            novo_passageiro.setPassageiro_id(txt_id.getText());
            novo_passageiro.setNome(txt_nome.getText());
            novo_passageiro.setOrigem(txt_origem.getText());
            novo_passageiro.setDestino(txt_destino.getText());
            novo_passageiro.setTipo_carro(txt_carro.getText());
            novo_passageiro.setCapacidade(txt_capacidade.getText());
            novo_passageiro.setPreco(txt_preco.getText());
            
            //Convertendo o objeto para um formato json
            Gson g = new Gson();
            java.lang.reflect.Type passageiro_novo_Type = new TypeToken<Passageiro>() {}.getType();
            String novo_json = g.toJson(novo_passageiro, passageiro_novo_Type);
            String url = "http://127.0.0.1:5000/passageiros/"+novo_passageiro.getPassageiro_id();
            ConsumindoServicos http = new ConsumindoServicos();
            //Chamando o método para enviar os dados para o servidor
            http.envioPost(url, novo_json, "POST");
        } catch (Exception ex) {
            Logger.getLogger(JFormPassageiro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_listarmotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarmotoristasActionPerformed
        try {
            //Listar todos os motoristas em um textfiedl
            ConsumindoServicos http = new ConsumindoServicos();
            String chamadaWS;
            chamadaWS = "http://127.0.0.1:5000/motoristas";
            String json = http.envioGet(chamadaWS);
            System.out.println(json);
            txt_motoristas.setText(json);
        } catch (Exception ex) {
            Logger.getLogger(JFormPassageiro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_listarmotoristasActionPerformed

    private void btn_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservaActionPerformed
        try {
            //Fazer a reserva:
            
            ConsumindoServicos http = new ConsumindoServicos();
            String motorista_id = txt_idmotorista.getText();
            
            //Buscando o motorista por meio di ID
            String chamadaWS_motorista = "http://127.0.0.1:5000/motoristas/"+motorista_id;
            String json_motorista = http.envioGet(chamadaWS_motorista);
            Motorista m = new Motorista();
            Gson gm = new Gson();
            java.lang.reflect.Type motoristaType = new TypeToken<Motorista>() {}.getType();
            m = gm.fromJson(json_motorista, motoristaType);
            //Verifica a disponibilidade do motorista:
            if(m.getDisponibilidade().equals("Sim")){
                //Altera a disponibilidade do motorista
                m.setDisponibilidade("Nao");
                java.lang.reflect.Type motorista_novo_Type = new TypeToken<Motorista>() {}.getType();
                String novo_json = gm.toJson(m, motorista_novo_Type);
                String url = "http://127.0.0.1:5000/motoristas/"+motorista_id;
                //Atualiza os dados do motorista por meio do método PUT
                http.envioPost(url, novo_json, "PUT");
                String id = txt_id.getText();
                String chamadaWS = "http://127.0.0.1:5000/passageiros/"+id;
                String json = http.envioGet(chamadaWS);
                System.out.println(json);
                Passageiro p = new Passageiro();
                Gson g = new Gson();
                java.lang.reflect.Type passageiroType = new TypeToken<Passageiro>() {}.getType();
                p = g.fromJson(json, passageiroType);

                //Fazendo a reserva utilizando os objetos de passageiro e motorista obtidos acima. 
                Reserva nova_reserva = new Reserva();
                nova_reserva.setReserva_id(txt_reserva.getText());

                nova_reserva.setPassageiro_id(txt_id.getText());
                nova_reserva.setMotorista_id(txt_idmotorista.getText());
                nova_reserva.setPassageiro(p.getNome());
                nova_reserva.setMotorista(m.getNome());
                nova_reserva.setOrigem(p.getOrigem());
                nova_reserva.setDestino(p.getDestino());
                nova_reserva.setTipo_carro(m.getTipo_carro());
                nova_reserva.setCapacidade(m.getCapacidade());
                nova_reserva.setPreco(m.getPreco());
                java.lang.reflect.Type reserva_novo_Type = new TypeToken<Reserva>() {}.getType();
                String novo_json_reserva = g.toJson(nova_reserva, reserva_novo_Type);
                String url_reserva = "http://127.0.0.1:5000/reservas/"+nova_reserva.getReserva_id();
                //Enviando a reserva para ser processada. 
                http.envioPost(url_reserva, novo_json_reserva, "POST");
                JOptionPane.showMessageDialog(null, "RESERVA REALIZADA!!: ");
            }else{
                JOptionPane.showMessageDialog(null, "MOTORISTA RESERVADO!: ");
            }
                

            } catch (Exception ex) {
                Logger.getLogger(JFormPassageiro.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_btn_reservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormPassageiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_listarmotoristas;
    private javax.swing.JButton btn_reserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_capacidade;
    private javax.swing.JTextField txt_carro;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idmotorista;
    private javax.swing.JTextPane txt_motoristas;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_origem;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_reserva;
    // End of variables declaration//GEN-END:variables
}
